### job 配置项
jobs:
  release:
    image: registry.erda.cloud/erda-actions/release-action:20210915-f80e952
    envs:
      BASE64_SWITCH: false
    resources:
      cpu: 0.2
      mem: 512
      disk: 128
